spring:
  application:
    name: soraka-discovery
server:
  port: 8001
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8001/eureka/

