spring:
  application:
    name: soraka-gateway
server:
  port: 8002
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
zuul:
  ignored-services: '**'
  routes:
    soraka-weixin: 'mp/**'
    soraka-admin: 'admin/**'
    soraka-auth: 'auth/**'
  sensitiveHeaders: Cookie,Set-Cookie
ribbon:
  ReadTimeout: 3000
#认证服务器地址
security:
  auth:
    server: http://localhost:8005
logging:
  level:
    com.soraka.auth: DEBUG
    org.springframework.security: DEBUG
